In [30]:
import pandas as pd
import matplotlib.pyplot as plt

from pathlib import Path
import os

In [31]:
data_dir = 'Sensor Board Update Initial Test'
data_path = Path(data_dir)

data_path

WindowsPath('Sensor Board Update Initial Test')

In [4]:
labels = {
    'A': '30 NM',
    'B': 'Loose',
    'C': 'Mix-45 Deg'
}

In [6]:
test_info_df = pd.read_csv(f'{data_dir}/Test.csv')
test_info_df

,Run,Test,Actuator,CCR Type,Controller,Wave Type 1,Start Freq 1,End Freq 1,Sweep Time 1,Amp 1,Wave Type 2,Start Freq 2,End Freq 2,Sweep Time 2,Amp 2,Start,End,Bolt Status,Location,Duration
0,A,10001,Subwoofer,CCT,Controller 12,Sweep,50.0,4000.0,0.3,110.0,NaN,NaN,NaN,NaN,NaN,1775576848,1775576851,30NM,VMF,3
1,A,10002,Subwoofer,CCT,Controller 12,Sweep,50.0,4000.0,0.3,110.0,NaN,NaN,NaN,NaN,NaN,1775576866,1775576869,30NM,VMF,3
2,A,10003,Subwoofer,CCT,Controller 12,Sweep,50.0,4000.0,0.3,110.0,NaN,NaN,NaN,NaN,NaN,1775576884,1775576887,30NM,VMF,3
3,A,10004,Subwoofer,CCT,Controller 12,Sweep,50.0,4000.0,0.3,110.0,NaN,NaN,NaN,NaN,NaN,1775576902,1775576905,30NM,VMF,3
4,A,10005,Subwoofer,CCT,Controller 12,Sweep,50.0,4000.0,0.3,110.0,NaN,NaN,NaN,NaN,NaN,1775576920,1775576923,30NM,VMF,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
643,B,60001,Subwoofer,CCT,Controller 12,Sweep,100.0,1000.0,0.3,100.0,NaN,NaN,NaN,NaN,NaN,1775586071,1775586074,Loose,VMF,3
644,B,60002,Subwoofer,CCT,Controller 12,Sweep,100.0,1000.0,0.3,100.0,NaN,NaN,NaN,NaN,NaN,1775586089,1775586092,Loose,VMF,3
645,B,60003,Subwoofer,CCT,Controller 12,Sweep,100.0,1000.0,0.3,100.0,NaN,NaN,NaN,NaN,NaN,1775586107,1775586110,Loose,VMF,3
646,B,60004,Subwoofer,CCT,Controller 12,Sweep,100.0,1000.0,0.3,100.0,NaN,NaN,NaN,NaN,NaN,1775586125,1775586128,Loose,VMF,3
647,B,60005,Subwoofer,CCT,Controller 12,Sweep,100.0,1000.0,0.3,100.0,NaN,NaN,NaN,NaN,NaN,1775586143,1775586146,Loose,VMF,3

In [11]:
test_info_df.groupby('Run').Test.nunique()

Run
A    216
B    216
C    216
Name: Test, dtype: int64

In [29]:
test_info_df['Location'].unique()

array(['VMF'], dtype=object)

In [7]:
test_info_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 648 entries, 0 to 647
Data columns (total 20 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Run           648 non-null    object
 1   Test          648 non-null    int64
 2   Actuator      648 non-null    object
 3   CCR Type      648 non-null    object
 4   Controller    648 non-null    object
 5   Wave Type 1   630 non-null    object
 6   Start Freq 1  630 non-null    float64
 7   End Freq 1    630 non-null    float64
 8   Sweep Time 1  630 non-null    float64
 9   Amp 1         630 non-null    float64
 10  Wave Type 2   558 non-null    object
 11  Start Freq 2  558 non-null    float64
 12  End Freq 2    558 non-null    float64
 13  Sweep Time 2  558 non-null    float64
 14  Amp 2         558 non-null    float64
 15  Start         648 non-null    int64
 16  End           648 non-null    int64
 17  Bolt Status   648 non-null    object
 18  Location      648 non-null    object
 19  Duration      648 non-null    int64
dtypes: float64(8), int64(4), object(8)
memory usage: 101.4+ KB

In [8]:
test_info_df.describe()

,Test,Start Freq 1,End Freq 1,Sweep Time 1,Amp 1,Start Freq 2,End Freq 2,Sweep Time 2,Amp 2,Start,End,Duration
count,648.000000,630.000000,630.000000,6.300000e+02,630.000000,558.000000,558.000000,5.580000e+02,558.0,6.480000e+02,6.480000e+02,648.000000
mean,34332.111111,66.666667,1083.333333,3.000000e-01,96.666667,558.333333,2550.000000,3.000000e-01,100.0,1.775579e+09,1.775579e+09,4.583333
std,17806.901159,23.588955,1358.056102,2.333321e-15,7.459483,728.329968,1735.289544,1.166780e-15,0.0,4.701563e+03,4.695800e+03,9.374362
min,101.000000,50.000000,100.000000,3.000000e-01,90.000000,50.000000,100.000000,3.000000e-01,100.0,1.775561e+09,1.775561e+09,3.000000
25%,20203.750000,50.000000,200.000000,3.000000e-01,90.000000,50.000000,200.000000,3.000000e-01,100.0,1.775576e+09,1.775576e+09,3.000000
50%,30602.500000,50.000000,600.000000,3.000000e-01,95.000000,125.000000,3500.000000,3.000000e-01,100.0,1.775580e+09,1.775580e+09,3.000000
75%,50301.250000,100.000000,1000.000000,3.000000e-01,100.000000,1000.000000,4000.000000,3.000000e-01,100.0,1.775583e+09,1.775583e+09,3.000000
max,60605.000000,100.000000,4000.000000,3.000000e-01,110.000000,2000.000000,4000.000000,3.000000e-01,100.0,1.775586e+09,1.775586e+09,60.000000

In [37]:
csv_files = []

for run in labels.keys():
    csv_files.extend(list((data_path/run).rglob("*.csv")))
    
len(csv_files)

8282

In [42]:
test_2_channels = []
test_3_channels = []

for csv_file in csv_files:
    if len(pd.read_csv(csv_file).columns) == 3:
        test_2_channels.append(csv_file)
    elif len(pd.read_csv(csv_file).columns) == 4:
        test_3_channels.append(csv_file)
        
len(test_2_channels), len(test_3_channels)

(3, 8279)

In [43]:
test_2_channels

[WindowsPath('Sensor Board Update Initial Test/A/50601/2521610325/combined_output.csv'),
 WindowsPath('Sensor Board Update Initial Test/B/50601/2521610325/combined_output.csv'),
 WindowsPath('Sensor Board Update Initial Test/C/50601/2521610325/combined_output.csv')]